---
- name: Backup running config router
  hosts: ExamRouter
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Get running-config from device
      cisco.ios.ios_command:
        commands:
          - show run
      register: config

    - name: Save running-config to local file
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "show_run_66070101_R1-Exam.txt"
      delegate_to: localhost