download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-network-5.1.0.tar.gz
format_version: 1.0.0
name: network
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/network/versions/5.1.0/
