download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-ios-11.1.1.tar.gz
format_version: 1.0.0
name: ios
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 11.1.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/ios/versions/11.1.1/
